### ISSUE TITLE
我想移除卡片的动效应该怎么修改

### ISSUE THREAD

**Issue by yokinanya** [Xinrea/JoiAsk-frontend#4]
就是移除掉鼠标移上去触发的动画

**Comment by Xinrea** [comment]
https://github.com/Xinrea/JoiAsk-frontend/blob/88c0946094b65aa50861cb957fc9a3e1e6d3a334/src/components/PostCard.svelte#L176-L178

卡片的鼠标动画触发回调是在这里设置的，去掉相应的事件处理，动效应该就不会触发了。

**Comment by yokinanya** [comment]
好了，谢谢
